### ISSUE TITLE
Outdated NPM package

### ISSUE THREAD

**Issue by veraldo** [argyleink/scrollyfills#13]
Hi, thanks for the polyfill!

FYI the main branch seems to be working fine, but seems like it's not the version that was published on NPM as it still errors server-side, which was solved by https://github.com/argyleink/scrollyfills/pull/11

As a workaround for now I'm using the latest commit as of this date directly on the package json like this:

`"scrollyfills": "github:argyleink/scrollyfills#b49b6d74af9b9e100d8a8660ed851f3fb212a8e1"`

Thanks

**Comment by argyleink** [comment]
v1.0.1 just published 👍🏻 
let me know if that doesnt resolve this issue
