### ISSUE TITLE
`scrollend` doesn't fire when user is in reduced motion

### ISSUE THREAD

**Issue by argyleink** [argyleink/scrollyfills#2]
tldr; instant programmatic scroll doesnt fire a scroll event, so tracking the scroll event won't be good enough.

**Comment by flackr** [comment]
I'm unable to reproduce scroll events not firing for instant programmatic scrolls, e.g. the demo I put together at https://jsbin.com/mewetab/edit?html,css,js,output fires the scroll event for the programmatic scroll.

**Comment by argyleink** [comment]
i can no longer repro either, must have just been on "my machine at that time" cuz i was baffled for an hour or so about it. but now can't cause it.
