### ISSUE TITLE
`scrollend` fires even if pointers are still down

### ISSUE THREAD

**Issue by argyleink** [argyleink/scrollyfills#4]
aka, this event can fire prematurely due to it's current timeout override strategy.

to reproduce, scroll partially then stop but keep your fingers on the track pad, notice it calls the callback. no pointers should be active in the scrollport or the callback shouldn't be made.

**Comment by flackr** [comment]
Yeah this is the harder part of scrollend to polyfill. If you think this is important, we could globally track fingers which are down and then assume that scrolls which start while a finger is down in that scroller are not done until that finger goes up.
